# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20171113_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
