# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171113_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='admin_of_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
