# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171113_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choir',
            name='perform_day',
        ),
        migrations.RemoveField(
            model_name='choir',
            name='perform_day_end_hour',
        ),
        migrations.RemoveField(
            model_name='choir',
            name='perform_day_start_hour',
        ),
    ]
