# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_choir_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='choristers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
