# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171114_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
