# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171114_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization'),
        ),
    ]
