# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_musicrecord'),
        ('api', '0013_auto_20171202_1620'),
    ]

    operations = [
    ]
