# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20171202_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='programmed_music',
            field=models.ManyToManyField(to='api.MusicRecord'),
        ),
    ]
