# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_programmed_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
