# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180201_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
