# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180202_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=3000)),
                ('music_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MusicRecord')),
            ],
        ),
    ]
