# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_musicresource'),
        ('api', '0021_auto_20180213_2232'),
    ]

    operations = [
    ]
