# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20180220_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicresource',
            name='field',
        ),
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('musicresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.MusicResource')),
                ('file_name', models.CharField(max_length=300)),
                ('file_type', models.CharField(max_length=10)),
            ],
            bases=('api.musicresource',),
        ),
        migrations.CreateModel(
            name='TextResource',
            fields=[
                ('musicresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.MusicResource')),
                ('field', models.CharField(max_length=3000)),
            ],
            bases=('api.musicresource',),
        ),
        migrations.AddField(
            model_name='musicresource',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
