# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20180222_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
