# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180220_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
