# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180227_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfield',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
