# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_programfield_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programfield',
            name='order',
            field=models.IntegerField(),
        ),
    ]
