# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180302_2148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programfield',
            unique_together=set([('order', 'music_record', 'event')]),
        ),
    ]
