# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprofile_profile_picture_link'),
        ('api', '0023_auto_20180227_2200'),
        ('api', '0028_auto_20180302_2148'),
    ]

    operations = [
    ]
