# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20180304_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfield',
            name='field_title',
            field=models.CharField(default='Title', max_length=500),
            preserve_default=False,
        ),
    ]
